services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playlist-backend
    env_file:
      - .env
    ports:
      - "5050:5000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:5000/playlist"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped